name: hex-2048 # you probably want to 'snapcraft register <name>'
base: core22 # the base snap is the execution environment for this snap
version: '1.0.0' # just for humans, typically '1.2+git' or '1.3.2'
title: Hex 2048
summary: Merge numbers on a hex grid to reach 2048! # 79 char long summary
description: |
  Hex 2048 is a captivating puzzle game that merges the classic 2048 gameplay with a hexagonal grid twist! Swipe your way through the hexagons, combining matching numbers to reach the elusive 2048 tile. 

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots

apps:
  hex-2048:
    command: bin/hex-2048-bin
    extensions: [gnome]
    plugs:
      - network
      - unity7
      - network-status

layout:
  /usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/webkit2gtk-4.1:
    bind: $SNAP/gnome-platform/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/webkit2gtk-4.0

parts:
  hex-2048:
    plugin: dump
    source: .
    organize:
      hex-2048-bin: bin/
